INSERT INTO developers (NAME, LAST_NAME) VALUES ('Karl', 'Gauss');
INSERT INTO developers (NAME, LAST_NAME) VALUES ('Daniel', 'Bernoulli');
INSERT INTO developers (NAME, LAST_NAME) VALUES ('Leonardo', 'Fibonacci');
INSERT INTO developers (NAME, LAST_NAME) VALUES ('Leonard', 'Euler');
INSERT INTO developers (NAME, LAST_NAME) VALUES ('Pierre', 'Fermat');
INSERT INTO developers (NAME, LAST_NAME) VALUES ('Isaac', 'Newton');
INSERT INTO developers (NAME, LAST_NAME) VALUES ('Rene', 'Descartes');
INSERT INTO developers (NAME, LAST_NAME) VALUES ('Blaise', 'Pascal');
INSERT INTO developers (NAME, LAST_NAME) VALUES ('Wilhelm', 'Leibniz');

commit;

INSERT INTO skills (skill) VALUES ('JAVA');
INSERT INTO skills (skill) VALUES ('C');
INSERT INTO skills (skill) VALUES ('C++');
INSERT INTO skills (skill) VALUES ('C#');
INSERT INTO skills (skill) VALUES ('PHP');
INSERT INTO skills (skill) VALUES ('Python');
INSERT INTO skills (skill) VALUES ('JavaScript');
INSERT INTO skills (skill) VALUES ('Delphi');
INSERT INTO skills (skill) VALUES ('Perl');
INSERT INTO skills (skill) VALUES ('Ruby');
commit;

INSERT INTO customers (customer) VALUES ('customer1');
INSERT INTO customers (customer) VALUES ('customer2');
INSERT INTO customers (customer) VALUES ('customer3');
INSERT INTO customers (customer) VALUES ('customer4');
INSERT INTO customers (customer) VALUES ('customer5');
INSERT INTO customers (customer) VALUES ('customer6');
INSERT INTO customers (customer) VALUES ('customer7');
INSERT INTO customers (customer) VALUES ('customer8');
INSERT INTO customers (customer) VALUES ('customer9');
INSERT INTO customers (customer) VALUES ('customer10');
commit;

INSERT INTO companies (company) VALUES ('company1');
INSERT INTO companies (company) VALUES ('company2');
INSERT INTO companies (company) VALUES ('company3');
INSERT INTO companies (company) VALUES ('company4');
INSERT INTO companies (company) VALUES ('company5');
INSERT INTO companies (company) VALUES ('company6');
INSERT INTO companies (company) VALUES ('company7');
INSERT INTO companies (company) VALUES ('company8');
INSERT INTO companies (company) VALUES ('company9');
INSERT INTO companies (company) VALUES ('company10');
commit;

update developers SET dev_company = 1 where ID%4 = 1;
update developers SET dev_company = 2 where ID%4 = 2;
update developers SET dev_company = 3 where ID%4 = 3;
update developers SET dev_company = 4 where ID%4 = 0;
commit;

INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (1, 1);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (2, 10);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (2, 1);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (3, 1);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (3, 10);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (3, 5);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (4, 2);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (5, 3);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (5, 4);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (6, 5);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (6, 6);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (6, 7);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (8, 6);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (8, 7);
INSERT INTO dev_project (DEVELOPER_ID, PROJECT_ID) VALUES  (9, 9);
commit;

INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (1, 1);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (2, 10);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (2, 1);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (3, 1);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (3, 10);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (3, 5);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (4, 2);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (5, 3);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (5, 4);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (6, 5);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (6, 6);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (6, 7);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (8, 6);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (8, 7);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (9, 9);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (9, 8);
INSERT INTO dev_skills (DEVELOPER_ID, SKILL_ID) VALUES  (9, 7);
    commit;

INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project1', 1, 1);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project2', 2, 10);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project3', 2, 1);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project4', 3, 1);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project5', 3, 10);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project6', 3, 5);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project7', 4, 2);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project8', 5, 3);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project9', 5, 4);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project10', 6, 5);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project11', 6, 6);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project12', 6, 7);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project13', 8, 6);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project14', 8, 7);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project15', 9, 9);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project16', 9, 8);
INSERT INTO projects (project, proj_company, proj_customers) VALUES  ('project17', 9, 7);
commit;
